// <auto-generated />
using System;
using CurrentAccount.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrentAccount.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220728154112_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CurrentAccount.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("balance")
                        .HasColumnType("int");

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CurrentAccount.Data.AccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerInfoId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("CurrentAccount.Data.CustomerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomersInfo");
                });

            modelBuilder.Entity("CurrentAccount.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountTransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CurrentAccount.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dory",
                            SurName = "Fakhry"
                        });
                });

            modelBuilder.Entity("CurrentAccount.Data.AccountTransaction", b =>
                {
                    b.HasOne("CurrentAccount.Data.CustomerInfo", null)
                        .WithMany("AccountTrans")
                        .HasForeignKey("CustomerInfoId");
                });

            modelBuilder.Entity("CurrentAccount.Data.Transaction", b =>
                {
                    b.HasOne("CurrentAccount.Data.AccountTransaction", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountTransactionId");
                });

            modelBuilder.Entity("CurrentAccount.Data.AccountTransaction", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CurrentAccount.Data.CustomerInfo", b =>
                {
                    b.Navigation("AccountTrans");
                });
#pragma warning restore 612, 618
        }
    }
}
